module.exports = {
    ADMINISTRATOR: 'Administrador',
    CREATE_INSTANT_INVITE: 'Criar convite instantâneo.',
    KICK_MEMBERS : 'Expulsar membros',
    BAN_MEMBERS: 'Banir Membros',
    MANAGE_CHANNELS : 'Gerenciar canais',
    MANAGE_GUILD : 'Gerenciar o servidor',
    ADD_REACTIONS : 'Adicionar reações',
    VIEW_AUDIT_LOG : 'Visualizar a auditoria',
    PRIORITY_SPEAKER : 'Palestrante pioritário',
    SEND_MESSAGES: 'Enviar mensagens',
    SEND_TTS_MESSAGES : 'Enivar mensagens em TTS',
    MANAGE_MESSAGES : 'Gerenciar mensagens',
    EMBED_LINKS : 'Inserir links',
    ATTACH_FILES: 'Anexar arquivos',
    READ_MESSAGE_HISTORY  : 'Ler o histórico de mensagens',
    MENTION_EVERYONE : 'Mencionar todos',
    USE_EXTERNAL_EMOJIS : 'Utilizar emojis externos',
    CONNECT : 'Conectar-se a um canal de voz',
    SPEAK : 'Falar em um canal de voz.',
    MUTE_MEMBERS : 'Silenciar membros',
    DEAFEN_MEMBERS  : 'Silenciar todos os membros',
    MOVE_MEMBERS : 'Mover membros do canal',
    USE_VAD : 'Usar detectção de voz para falar',
    CHANGE_NICKNAME: 'Alterar apelido',
    MANAGE_NICKNAMES  : 'Gerenciar apelidos',
    MANAGE_ROLES : 'Gerenciar cargos',
    MANAGE_WEBHOOKS : 'Gerenciar WebHooks',
    MANAGE_EMOJIS : 'Gerenciar emojis'
}